# Generated by Django 5.2.8 on 2026-03-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_add_userprofile_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='paper',
            field=models.CharField(blank=True, choices=[('rgn_med_surg', 'RGN – Medical–Surgical Nursing'), ('rgn_community_health', 'RGN – Community Health Nursing'), ('rgn_general', 'RGN – General Nursing Paper'), ('rm_midwifery_obstetrics', 'RM – Midwifery & Obstetrics'), ('rm_community_based', 'RM – Community-Based Midwifery'), ('rm_general', 'RM – General Midwifery Paper'), ('rcn_community_phc', 'RCN – Community Health & Primary Health Care'), ('rcn_maternal_child', 'RCN – Maternal & Child Health'), ('rcn_general', 'RCN – General Community Nursing Paper')], default='', help_text='Specific written paper (e.g. Medical–Surgical, Community Health, General Paper).', max_length=40),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='program',
            field=models.CharField(blank=True, choices=[('rgn', 'Registered General Nursing (RGN)'), ('rm', 'Registered Midwifery (RM)'), ('rcn', 'Registered Community Nursing (RCN)')], default='', help_text='Which nursing programme this question belongs to (RGN, RM, or RCN).', max_length=10),
        ),
    ]
