# Generated by Django 5.2.8 on 2026-03-02 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_casestudyaccess_resourcebookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, default='', max_length=10)),
                ('paper', models.CharField(blank=True, default='', max_length=40)),
                ('timed', models.BooleanField(default=False, help_text='If true, student practiced under timed conditions (50s per question).')),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('questions', models.JSONField(default=list, help_text='List of MCQQuestion IDs for this session in order.')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('order_index', models.PositiveIntegerField(help_text='1-based index within the session.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_answers', to='website.mcqquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_answers', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='website.practicesession')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
