# Generated by Django 5.2.8 on 2026-03-06 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_practicesession_practiceanswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practiceanswer',
            unique_together={('session', 'order_index')},
        ),
        migrations.AddField(
            model_name='practiceanswer',
            name='answer_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='practiceanswer',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='practiceanswer',
            name='question_supabase_id',
            field=models.CharField(blank=True, help_text='Supabase mcq_questions id when question is from Supabase.', max_length=64),
        ),
        migrations.AddField(
            model_name='practiceanswer',
            name='question_text',
            field=models.TextField(blank=True, help_text='Snapshot for review when question is from Supabase.'),
        ),
        migrations.AlterField(
            model_name='practiceanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_answers', to='website.mcqquestion'),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='questions',
            field=models.JSONField(default=list, help_text='List of Supabase mcq_questions ids (str or int) in order.'),
        ),
    ]
