# Generated by Django 5.2.8 on 2026-03-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_add_mcq_case_study_books_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='answer_explanation',
            field=models.TextField(blank=True, help_text='Optional rationale for the correct answer.'),
        ),
    ]
