# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='file_url',
            field=models.URLField(blank=True, help_text='Optional: Supabase case_study bucket URL or external link', max_length=500),
        ),
    ]
