# Generated by Django 5.2.8 on 2026-03-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_case_study_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='program',
            field=models.CharField(blank=True, choices=[('', '-- Select program --'), ('general', 'General Nursing'), ('midwifery', 'Midwifery'), ('community', 'Community Nursing')], default='', help_text='Nursing program the student is enrolled in.', max_length=20),
        ),
    ]
