# Generated by Django 5.2.8 on 2026-03-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_add_mcq_program_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='website.casestudy')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_study_accesses', to='website.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user_email', 'case_study')},
            },
        ),
        migrations.CreateModel(
            name='ResourceBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='website.bookorslide')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user_email', 'resource')},
            },
        ),
    ]
